### ISSUE TITLE
about spell107

### ISSUE THREAD

**Issue by LostTemple1990** [Gaboros/VenturePlan#45] opened 2021-07-12 05:38 UTC
this spell may deal **BOTH** 150 damageATK and additional damage in 3 turns ,instead of 150 damageATK in only one turn
![QQ截图20210712133022](https://user-images.githubusercontent.com/17272616/125235673-68fa8900-e315-11eb-9f20-90ce77cbe459.png)
i've tried to explain this during this picture above due to i used this chinese client
It dealt 804 damage(level 57,base atk 402) with damageATK 603 and plusDamageDealtATK 201 in turn 2

**Comment by MMOSimca** [comment] 2021-07-12 11:29
There was some discussion about this in #42. This sounds like it is a bug on Blizzard's end. Can you provide a log with more detail or explain the functionality (i.e. does this damage last 3 turns or 4 while skipping turn 1, as is typical for DoTs - they usually last one turn longer than stated)? Part of the problem is that this spell does such an insane amount of damage, mobs don't survive long enough to see what happens in future turns.

**Comment by MMOSimca** [comment] 2021-07-12 16:10
Fixed in https://github.com/Gaboros/VenturePlan/commit/2c78405af562a0d6283e626ff40d2cb2c13e50d1

**Closed by MMOSimca** 2021-07-12 16:10 UTC
